language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: junior-maker
  api_key:
    secure: OV4BOMi2XLnS72nvFoZ7197wp2H2JeARweBxtVGegO3Rc7NfzsclATgdtFqj077h1Ovo4eguimKPC1L0T2L2FOJfyuI5RCvBWo4TD9CKyvYXyJuYV7NXHPP5D4mWS5KQs9k3jebAjeQBH8LiepbKj6ZmCfBxne+OjY8G+5T0ktF5v8za+STAlfGTxRgFZk9gAFdcO1X0Dl65dFOdZZJszxQZsHGcpIITzuO53TLYSSXHie3YCubJ1eZ9kd36ohxRRVW7Xicou5/Zelbsaf+q7wSBFwQ8++xk7VmHkaEklK/kWDgsNnfOJ4YV0LKnaTSUjUV+x/P0c+8aJJ4p0A4vvKLkPN1sswzK23Xm1bbWJJ3EoCcgvkNsX3auFtoAqHfFa6ACZjQXhisYq4k1sgppGKhOAyZw/IwaPz09I0C41fbkvFSAioohi4/IMkn2Cg/96aR79Kw5d58K4uYBkFJIcVjyJo+X6xYgAJYQbWXfLPghRj4Jr5b3HuWc50A4SGK33AgBvWq8m/ef8dJhwHP05ph3RZVvS7RZAwhU2dYAYhQBWLUL2Dy78/OZMUqJWYVobs1lOv/RqNnb2mndCwFJqLUu2A+MBJIPSdIyBzyomMqehoCNRYpwDAfpJNXAJK8jC2MHWvToCWNIXzAWcPFBOQ+fuqtnC9Mh6REg5ygjY4E=
true:
  branch: master
